### PR TITLE
add test for CtxIdx

### PR DESCRIPTION
**Pull request by shawnps**

### CODE REVIEW

**Comment by shawnps** [comment]
@saxon-milton this should help us in refactoring `CtxIdx` for https://github.com/ausocean/h264decode/issues/10

I have some other code on my local that I'll push up afterwards that uses a map for that function rather than the nested switches.

Please note I discovered that [this block](https://github.com/ausocean/h264decode/blob/master/h264/cabac.go#L719-L723) in `cabac.go` may be incorrect - `ctxIdx` is being set to `0` but then the function immediately returns `NaCtxId`, meaning the assignment has no effect.

**Review by saxon-milton — APPROVED** [review]
Looks good. Maybe just comment the test func.

**Comment by saxon-milton** [comment]
@shawnps good to hear you have a map sorted. How you do intend on handling the entries that require additional processes ? 

In regards to incorrect code - I would not be be surprised to find things that don't actually work. When we first forked this repo, there was almost no testing of functionality to show its validity. For this reason, testing is definitely one of our primary goals at this stage.

**Comment by saxon-milton** [comment]
@shawnps feel free to create an issue to correct the problem, otherwise you could just do it when you implement the map.

**Comment by shawnps** [comment]
> @shawnps good to hear you have a map sorted. How you do intend on handling the entries that require additional processes ?

@saxon-milton I was thinking of leaving those alone at first, and just using the map to reduce the footprint of the nested switches. I'll open a PR after this and you can take a look soon.

**Pull request merged**
