### PR TITLE
Run gofmt -s

### PR DESCRIPTION
**Pull request by shawnps**
@saxon-milton this looks a bit scary but actually no functionality changes with this PR - `gofmt -s` simplifies code to make it more readable. Everything should run as it did previously.

### CODE REVIEW

**Review by saxon-milton — APPROVED** [review]

**Comment by shawnps** [comment]
@saxon-milton I just noticed you have a PR here: https://github.com/ausocean/h264decode/pull/1

Will that be merged in soon? If so I'll wait until that's merged and then re-run `gofmt -s` on the new code (to avoid causing merge conflicts in your branch).

**Comment by saxon-milton** [comment]
> @saxon-milton I just noticed you have a PR here: #1
> 
> Will that be merged in soon? If so I'll wait until that's merged and then re-run `gofmt -s` on the new code.

@shawnps Good point actually. I might have touched some of the same code. I would like to merge that soon, but feel free to do a review if you'd like. I do have Alan's approval but the more the merrier :)

**Comment by shawnps** [comment]
@saxon-milton updated PR after your push

**Comment by saxon-milton** [comment]
@shawnps great! You can merge imo.

**Comment by shawnps** [comment]
@saxon-milton sure I'll go ahead, no functionality changes with this. Thanks!

**Pull request merged**
